#!/usr/bin/bash
# Change below values accordingly to you setup

export PUBLIC_IP4=0.0.0.0
export PUBLIC_IP6=000:000:000:000::
export DRUMEE_DOMAIN_NAME=examle.org
export ADMIN_EMAIL="" # Will be used to sign in as your Drumee admin

# Optional setting
export STORAGE_BACKUP="" # [user@host-or-ip:]/path/
export DRUMEE_DESCRIPTION="My Drumee Box"
export ACME_EMAIL_ACCOUNT="" # Provived to ssl.com for SSL certificates sign defaulted to ADMIN_EMAIL

# DO NOT CHANGE below this line
export DRUMEE_REPO=app.drumee.com
export INFRA_COMPONENTS=all
